version: 2

sources:
  - name: silver_cloud
    database: hive_metastore
    schema: silver
    tables:
      - name: atm_master
      - name: cards
      - name: cards_data
      - name: users_data
        identifier: customers
      - name: wallet
      - name: out_of_cash
      - name: kaggle_transactions