banking_local:
  target: dev
  outputs:
    dev:
      type: duckdb
      path: "D:/NTI INTERNSHIP/Airflow/Banking_pipeline/local_warehouse/banking.duckdb"
      schema: banking_dev
      threads: 4
      extensions:
        - parquet
        - json
      external_root: "D:/NTI INTERNSHIP/Airflow/Banking_pipeline/local_warehouse/delta/silver"

banking_pipeline:
  target: prod
  outputs:
    prod:
      type: databricks
      host: adb-7405618947472672.12.azuredatabricks.net
      http_path: /sql/protocolv1/o/7405618947472672/0624-204714-iiizo5c0
      token: "{{ env_var('DATABRICKS_TOKEN') }}"
      catalog: hive_metastore
      schema: silver
      threads: 4 